//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANCHAUCANH.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> MaPhanLoai { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> DonGiaBanNhoNhat { get; set; }
        public Nullable<decimal> DonGiaBanLonNhat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MoTaNgan { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<bool> NoiBat { get; set; }
        public Nullable<int> MaPhanLoaiPhu { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }
    }
}
